#!/usr/bin/env bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/common.sh"

usage() {
  cat >&2 <<'EOF'
Usage: ./scripts/generate-martin-config.sh

Generates martin/config.yaml from:
- data/published/<catalogue>/current.mbtiles
- data/styles/<catalogue>/*.json

Style IDs are derived from file paths:
- data/styles/basemap/default.json -> basemap
- data/styles/basemap/labels.json  -> basemap-labels
EOF
}

main() {
  load_env
  ensure_directories

  if [[ $# -gt 0 ]]; then
    case "$1" in
      -h|--help)
        usage
        exit 0
        ;;
      *)
        usage
        exit 1
        ;;
    esac
  fi

  require_command python3

  local temp_config
  temp_config=$(mktemp "${MARTIN_CONFIG_PATH}.XXXXXX")
  trap 'rm -f -- "${temp_config}"' EXIT

  REPO_ROOT="${REPO_ROOT}" \
  DATA_PUBLISHED_DIR="${DATA_PUBLISHED_DIR}" \
  STYLES_DIR="${STYLES_DIR}" \
  DEFAULT_CATALOGUE="${DEFAULT_CATALOGUE}" \
  python3 - "${temp_config}" <<'PY'
import json
import os
from pathlib import Path
import re
import sys

slug_re = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]*$")
published_dir = Path(os.environ["DATA_PUBLISHED_DIR"])
styles_dir = Path(os.environ["STYLES_DIR"])
target_path = Path(sys.argv[1])


def fail(message: str) -> None:
    raise SystemExit(message)


def validate_slug(value: str, label: str) -> None:
    if not slug_re.match(value):
        fail(f"invalid {label}: {value!r}")


def style_id_for_path(path: Path) -> str:
    rel = path.relative_to(styles_dir)
    if len(rel.parts) != 2:
        fail(f"style file must live under data/styles/<catalogue>/: {rel}")

    catalogue = rel.parts[0]
    style_name = path.stem
    validate_slug(catalogue, "catalogue name")
    validate_slug(style_name, "style file name")
    return catalogue if style_name == "default" else f"{catalogue}-{style_name}"


def validate_style(style_path: Path, style_id: str, catalogue_names) -> None:
    try:
        data = json.loads(style_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON in {style_path}: {exc}")

    if data.get("version") != 8:
        fail(f"style {style_id} must use MapLibre style version 8")

    sources = data.get("sources")
    if not isinstance(sources, dict) or not sources:
        fail(f"style {style_id} must define at least one source")

    for source_id, source in sources.items():
        if not isinstance(source, dict):
            fail(f"style {style_id} source {source_id} must be an object")

        source_url = source.get("url")
        if isinstance(source_url, str) and source_url.startswith("/"):
            catalogue = source_url.strip("/").split("/", 1)[0]
            if catalogue_names and catalogue not in catalogue_names:
                fail(
                    f"style {style_id} references /{catalogue}, but no published catalogue "
                    f"named {catalogue!r} exists"
                )

    for layer in data.get("layers", []):
        if not isinstance(layer, dict):
            fail(f"style {style_id} contains a non-object layer")
        layer_source = layer.get("source")
        if layer_source is not None and layer_source not in sources:
            fail(f"style {style_id} layer {layer.get('id', '<unknown>')} references missing source {layer_source!r}")


catalogues = []
if published_dir.exists():
    for entry in sorted(published_dir.iterdir(), key=lambda item: item.name):
        if not entry.is_dir():
            continue
        validate_slug(entry.name, "catalogue name")
        current = entry / "current.mbtiles"
        if current.exists() or current.is_symlink():
            catalogues.append((entry.name, f"/data/published/{entry.name}/current.mbtiles"))

catalogue_names = {name for name, _ in catalogues}

styles = []
seen_style_ids = set()
if styles_dir.exists():
    for style_path in sorted(styles_dir.glob("*/*.json")):
        style_id = style_id_for_path(style_path)
        validate_slug(style_id, "style id")
        if style_id in seen_style_ids:
            fail(f"duplicate style id: {style_id}")
        validate_style(style_path, style_id, catalogue_names)
        seen_style_ids.add(style_id)
        rel_path = style_path.relative_to(styles_dir)
        styles.append((style_id, f"/data/styles/{rel_path.as_posix()}"))

lines = [
    "# Generated by scripts/generate-martin-config.sh. Do not edit by hand.",
    "listen_addresses: 0.0.0.0:3000",
    "cors: true",
    "",
    "mbtiles:",
]

if catalogues:
    lines.append("  sources:")
    for name, path in catalogues:
        lines.append(f"    {name}: {path}")
else:
    lines.append("  sources: {}")

lines.extend(["", "styles:"])
if styles:
    lines.append("  sources:")
    for style_id, path in styles:
        lines.append(f"    {style_id}: {path}")
else:
    lines.append("  sources: {}")

target_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

  mv -f -- "${temp_config}" "${MARTIN_CONFIG_PATH}"
  chmod 0644 "${MARTIN_CONFIG_PATH}"
  trap - EXIT

  log "generated ${MARTIN_CONFIG_PATH}"
  printf '%s\n' "${MARTIN_CONFIG_PATH}"
}

main "$@"
